# Generated by Django 4.2.2 on 2023-06-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
